#!/usr/bin/env python3
"""Generate a tiny SYNTHETIC corpus so the pipeline is runnable with no data.

The audio is generated tones and noise, and the "transcripts" are mechanical
recombinations of a handful of Romanized Kokborok words. This is scaffolding
for smoke tests ONLY - it is not real language data, carries no linguistic
information, and must never be used to report a WER or be mistaken for a
corpus. Real recordings belong in data/raw.

    python scripts/make_fixture.py
    python scripts/make_fixture.py --speakers 6 --per-speaker 8 --layout manifest
"""

from __future__ import annotations

import argparse
import csv
import logging
import shutil
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("make_fixture")

SAMPLE_RATE = 16_000

# A few Romanized Kokborok words, used only to make the fixture transcripts
# look structurally like the real thing (Latin script, the "w" vowel).
WORDS = ["nwng", "bubagra", "tamwi", "ang", "kwlai", "hamjak", "nukhung", "borok", "sikla", "kok"]


def synth_clip(speaker_index: int, utt_index: int, seconds: float) -> np.ndarray:
    """Deterministic per-(speaker, utterance) waveform with a speaker-ish pitch."""
    rng = np.random.default_rng(1000 * speaker_index + utt_index)
    t = np.linspace(0.0, seconds, int(SAMPLE_RATE * seconds), endpoint=False, dtype=np.float32)
    f0 = 90.0 + 25.0 * speaker_index  # crude "speaker identity"
    wave = np.zeros_like(t)
    for harmonic, gain in ((1, 0.6), (2, 0.25), (3, 0.12)):
        wave += gain * np.sin(2 * np.pi * f0 * harmonic * t)
    # Syllable-rate envelope so it is not a constant drone.
    envelope = 0.5 * (1.0 + np.sin(2 * np.pi * 3.5 * t))
    wave = wave * envelope + 0.01 * rng.standard_normal(t.shape).astype(np.float32)
    peak = float(np.max(np.abs(wave))) or 1.0
    return (0.7 * wave / peak).astype(np.float32)


def synth_transcript(speaker_index: int, utt_index: int) -> str:
    rng = np.random.default_rng(50_000 + 1000 * speaker_index + utt_index)
    n_words = int(rng.integers(3, 7))
    return " ".join(str(w) for w in rng.choice(WORDS, size=n_words, replace=True))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", default="data/fixtures/raw", help="Output directory")
    parser.add_argument("--speakers", type=int, default=4)
    parser.add_argument("--per-speaker", type=int, default=5)
    parser.add_argument("--layout", choices=["pairs", "manifest"], default="pairs")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing fixture")
    args = parser.parse_args()

    import soundfile as sf

    root = Path(__file__).resolve().parents[1]
    out_dir = Path(args.out)
    if not out_dir.is_absolute():
        out_dir = root / out_dir

    if out_dir.exists() and any(out_dir.iterdir()):
        if not args.force:
            logger.info("Fixture already present at %s (use --force to regenerate)", out_dir)
            return 0
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, str]] = []
    for s in range(args.speakers):
        speaker = f"spk{s + 1:02d}"
        speaker_dir = out_dir / speaker if args.layout == "pairs" else out_dir / "audio"
        speaker_dir.mkdir(parents=True, exist_ok=True)
        for i in range(args.per_speaker):
            seconds = 1.0 + 0.4 * ((s + i) % 5)
            audio = synth_clip(s, i, seconds)
            transcript = synth_transcript(s, i)
            name = f"utt{i:03d}" if args.layout == "pairs" else f"{speaker}_utt{i:03d}"
            wav_path = speaker_dir / f"{name}.wav"
            sf.write(str(wav_path), audio, SAMPLE_RATE)
            if args.layout == "pairs":
                wav_path.with_suffix(".txt").write_text(transcript + "\n", encoding="utf-8")
            else:
                rows.append(
                    {
                        "audio_path": str(wav_path.relative_to(out_dir)),
                        "transcript": transcript,
                        "speaker_id": speaker,
                    }
                )

    if args.layout == "manifest":
        manifest_path = out_dir / "manifest.csv"
        with manifest_path.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=["audio_path", "transcript", "speaker_id"])
            writer.writeheader()
            writer.writerows(rows)
        logger.info("Wrote %s", manifest_path)

    (out_dir / "README.txt").write_text(
        "SYNTHETIC FIXTURE - generated by scripts/make_fixture.py.\n"
        "Tones and noise, not speech. The transcripts are random word\n"
        "recombinations, not real Kokborok utterances. For smoke tests only:\n"
        "never report metrics computed on this data.\n",
        encoding="utf-8",
    )

    total = args.speakers * args.per_speaker
    logger.info("Generated %d synthetic clips from %d speakers in %s (%s layout)",
                total, args.speakers, out_dir, args.layout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
